"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-05 17:34:36.476935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# audit_log is append-only. Rows may only be removed by the retention / shop-deletion job, which
# opts in for its transaction with `SET LOCAL storeops.audit_purge = 'on'`.
AUDIT_LOG_GUARD = """
CREATE OR REPLACE FUNCTION audit_log_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('storeops.audit_purge', true) = 'on' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'audit_log is append-only (% not allowed)', TG_OP;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shops",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "demo",
                "live",
                name="shop_mode",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "uninstalled",
                name="shop_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "plan",
            sa.Enum(
                "free",
                "growth",
                "pro",
                name="plan",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("access_token_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("scopes", sa.String(length=1024), nullable=True),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uninstalled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_deletion_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("mode IN ('demo', 'live')", name=op.f("ck_shops_shop_mode")),
        sa.CheckConstraint("plan IN ('free', 'growth', 'pro')", name=op.f("ck_shops_plan")),
        sa.CheckConstraint(
            "status IN ('active', 'uninstalled')", name=op.f("ck_shops_shop_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shops")),
        sa.UniqueConstraint("domain", name=op.f("uq_shops_domain")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "agent_configs",
        sa.Column(
            "agent",
            sa.Enum(
                "orchestrator",
                "fraud_guard",
                "inventory_planner",
                "cart_recovery",
                "support",
                "review_reputation",
                "revenue_analyst",
                "pricing_advisor",
                name="agent_name",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "autonomy",
            sa.Enum(
                "off",
                "suggest",
                "auto",
                name="autonomy",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("daily_action_cap", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("tone", sa.String(length=64), nullable=False),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "agent IN ('orchestrator', 'fraud_guard', 'inventory_planner', 'cart_recovery', 'support', 'review_reputation', 'revenue_analyst', 'pricing_advisor')",
            name=op.f("ck_agent_configs_agent_name"),
        ),
        sa.CheckConstraint(
            "autonomy IN ('off', 'suggest', 'auto')", name=op.f("ck_agent_configs_autonomy")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_agent_configs_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_configs")),
        sa.UniqueConstraint("shop_id", "agent", name=op.f("uq_agent_configs_shop_id_agent")),
    )
    op.create_index(op.f("ix_agent_configs_shop_id"), "agent_configs", ["shop_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "system",
                "agent",
                "user",
                name="actor_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('system', 'agent', 'user')", name=op.f("ck_audit_log_actor_type")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_audit_log_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_shop_id"), "audit_log", ["shop_id"], unique=False)
    op.create_index(
        "ix_audit_log_shop_occurred", "audit_log", ["shop_id", "occurred_at"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("shopify_id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("orders_count", sa.Integer(), nullable=False),
        sa.Column("total_spent_minor", sa.BigInteger(), nullable=False),
        sa.Column("accepts_marketing", sa.Boolean(), nullable=False),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_customers_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("shop_id", "shopify_id", name=op.f("uq_customers_shop_id_shopify_id")),
    )
    op.create_index(op.f("ix_customers_shop_id"), "customers", ["shop_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "viewer",
                name="role",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'viewer')", name=op.f("ck_memberships_role")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_memberships_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("shop_id", "user_id", name=op.f("uq_memberships_shop_id_user_id")),
    )
    op.create_index(op.f("ix_memberships_shop_id"), "memberships", ["shop_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "in_app",
                "email",
                "sms",
                "whatsapp",
                name="notification_channel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "info",
                "warning",
                "critical",
                name="severity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "channel IN ('in_app', 'email', 'sms', 'whatsapp')",
            name=op.f("ck_notifications_notification_channel"),
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')", name=op.f("ck_notifications_severity")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_notifications_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_shop_created", "notifications", ["shop_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_shop_id"), "notifications", ["shop_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("shopify_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("handle", sa.String(length=255), nullable=False),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("product_type", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("shopify_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_products_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("shop_id", "shopify_id", name=op.f("uq_products_shop_id_shopify_id")),
    )
    op.create_index(op.f("ix_products_shop_id"), "products", ["shop_id"], unique=False)
    op.create_table(
        "shop_settings",
        sa.Column("kill_switch", sa.Boolean(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column("fraud_threshold", sa.Integer(), nullable=False),
        sa.Column("max_discount_pct", sa.Integer(), nullable=False),
        sa.Column("refund_ceiling_minor", sa.Integer(), nullable=False),
        sa.Column("alert_email", sa.String(length=320), nullable=True),
        sa.Column("support_email", sa.String(length=320), nullable=True),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("physical_address", sa.String(length=512), nullable=True),
        sa.Column(
            "alert_channels",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_shop_settings_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_settings")),
        sa.UniqueConstraint("shop_id", name=op.f("uq_shop_settings_shop_id")),
    )
    op.create_index(op.f("ix_shop_settings_shop_id"), "shop_settings", ["shop_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column(
            "plan",
            sa.Enum(
                "free",
                "growth",
                "pro",
                name="plan",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "frozen",
                "cancelled",
                name="subscription_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.Enum(
                "none",
                "shopify",
                "stripe",
                name="billing_provider",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("plan IN ('free', 'growth', 'pro')", name=op.f("ck_subscriptions_plan")),
        sa.CheckConstraint(
            "provider IN ('none', 'shopify', 'stripe')",
            name=op.f("ck_subscriptions_billing_provider"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'frozen', 'cancelled')",
            name=op.f("ck_subscriptions_subscription_status"),
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_subscriptions_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_index(op.f("ix_subscriptions_shop_id"), "subscriptions", ["shop_id"], unique=False)
    op.create_table(
        "usage_counters",
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_usage_counters_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_counters")),
        sa.UniqueConstraint(
            "shop_id", "period", "metric", name=op.f("uq_usage_counters_shop_id_period_metric")
        ),
    )
    op.create_index(op.f("ix_usage_counters_shop_id"), "usage_counters", ["shop_id"], unique=False)
    op.create_table(
        "webhook_events",
        sa.Column("webhook_id", sa.String(length=128), nullable=False),
        sa.Column("topic", sa.String(length=64), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "shopify",
                "simulator",
                "reconciliation",
                name="event_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "queued",
                "processing",
                "processed",
                "failed",
                "skipped",
                name="webhook_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "source IN ('shopify', 'simulator', 'reconciliation')",
            name=op.f("ck_webhook_events_event_source"),
        ),
        sa.CheckConstraint(
            "status IN ('received', 'queued', 'processing', 'processed', 'failed', 'skipped')",
            name=op.f("ck_webhook_events_webhook_status"),
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_webhook_events_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint("webhook_id", name=op.f("uq_webhook_events_webhook_id")),
    )
    op.create_index(op.f("ix_webhook_events_shop_id"), "webhook_events", ["shop_id"], unique=False)
    op.create_index(
        "ix_webhook_events_shop_status", "webhook_events", ["shop_id", "status"], unique=False
    )
    op.create_index(op.f("ix_webhook_events_topic"), "webhook_events", ["topic"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column(
            "agent",
            sa.Enum(
                "orchestrator",
                "fraud_guard",
                "inventory_planner",
                "cart_recovery",
                "support",
                "review_reputation",
                "revenue_analyst",
                "pricing_advisor",
                name="agent_name",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("trigger_event_id", sa.Uuid(), nullable=True),
        sa.Column("trigger_topic", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "failed",
                "skipped",
                name="run_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "inputs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("used_fallback", sa.Boolean(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "agent IN ('orchestrator', 'fraud_guard', 'inventory_planner', 'cart_recovery', 'support', 'review_reputation', 'revenue_analyst', 'pricing_advisor')",
            name=op.f("ck_agent_runs_agent_name"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed', 'skipped')",
            name=op.f("ck_agent_runs_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_agent_runs_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["trigger_event_id"],
            ["webhook_events.id"],
            name=op.f("fk_agent_runs_trigger_event_id_webhook_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        "ix_agent_runs_shop_agent_started",
        "agent_runs",
        ["shop_id", "agent", "started_at"],
        unique=False,
    )
    op.create_index(op.f("ix_agent_runs_shop_id"), "agent_runs", ["shop_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("shopify_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("checkout_token", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal_minor", sa.BigInteger(), nullable=False),
        sa.Column("discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("refunded_minor", sa.BigInteger(), nullable=False),
        sa.Column("financial_status", sa.String(length=32), nullable=True),
        sa.Column("fulfillment_status", sa.String(length=32), nullable=True),
        sa.Column("shipping_country", sa.String(length=2), nullable=True),
        sa.Column("billing_country", sa.String(length=2), nullable=True),
        sa.Column("source_name", sa.String(length=64), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("is_held", sa.Boolean(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shopify_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_orders_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_orders_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("shop_id", "shopify_id", name=op.f("uq_orders_shop_id_shopify_id")),
    )
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_orders_shop_id"), "orders", ["shop_id"], unique=False)
    op.create_index("ix_orders_shop_processed", "orders", ["shop_id", "processed_at"], unique=False)
    op.create_table(
        "reviews",
        sa.Column(
            "source",
            sa.Enum(
                "shopify",
                "judgeme",
                "google",
                "simulator",
                name="review_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author_name", sa.String(length=128), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("sentiment_label", sa.String(length=16), nullable=True),
        sa.Column("reply_draft", sa.Text(), nullable=True),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "source IN ('shopify', 'judgeme', 'google', 'simulator')",
            name=op.f("ck_reviews_review_source"),
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_reviews_rating_range")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_reviews_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_reviews_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint(
            "shop_id", "source", "external_id", name=op.f("uq_reviews_shop_id_source_external_id")
        ),
    )
    op.create_index(op.f("ix_reviews_shop_id"), "reviews", ["shop_id"], unique=False)
    op.create_table(
        "variants",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("shopify_id", sa.BigInteger(), nullable=False),
        sa.Column("inventory_item_id", sa.BigInteger(), nullable=True),
        sa.Column("sku", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("price_minor", sa.BigInteger(), nullable=False),
        sa.Column("cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("inventory_quantity", sa.Integer(), nullable=False),
        sa.Column("reorder_point", sa.Integer(), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_variants_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variants")),
        sa.UniqueConstraint("shop_id", "shopify_id", name=op.f("uq_variants_shop_id_shopify_id")),
    )
    op.create_index(
        op.f("ix_variants_inventory_item_id"), "variants", ["inventory_item_id"], unique=False
    )
    op.create_index(op.f("ix_variants_product_id"), "variants", ["product_id"], unique=False)
    op.create_index(op.f("ix_variants_shop_id"), "variants", ["shop_id"], unique=False)
    op.create_table(
        "action_proposals",
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "agent",
            sa.Enum(
                "orchestrator",
                "fraud_guard",
                "inventory_planner",
                "cart_recovery",
                "support",
                "review_reputation",
                "revenue_analyst",
                "pricing_advisor",
                name="agent_name",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum(
                "low",
                "medium",
                "high",
                name="risk_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "preview",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "approved",
                "rejected",
                "executed",
                "failed",
                "expired",
                name="proposal_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "agent IN ('orchestrator', 'fraud_guard', 'inventory_planner', 'cart_recovery', 'support', 'review_reputation', 'revenue_analyst', 'pricing_advisor')",
            name=op.f("ck_action_proposals_agent_name"),
        ),
        sa.CheckConstraint(
            "risk_level IN ('low', 'medium', 'high')", name=op.f("ck_action_proposals_risk_level")
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'approved', 'rejected', 'executed', 'failed', 'expired')",
            name=op.f("ck_action_proposals_proposal_status"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_action_proposals_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_action_proposals_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_proposals")),
    )
    op.create_index(
        op.f("ix_action_proposals_shop_id"), "action_proposals", ["shop_id"], unique=False
    )
    op.create_index(
        "ix_action_proposals_shop_status", "action_proposals", ["shop_id", "status"], unique=False
    )
    op.create_table(
        "checkouts",
        sa.Column("shopify_id", sa.BigInteger(), nullable=True),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "line_items",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("recovery_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "abandoned",
                "recovered",
                "completed",
                name="checkout_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reminders_sent", sa.Integer(), nullable=False),
        sa.Column("last_reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovered_order_id", sa.Uuid(), nullable=True),
        sa.Column("shopify_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shopify_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'abandoned', 'recovered', 'completed')",
            name=op.f("ck_checkouts_checkout_status"),
        ),
        sa.CheckConstraint(
            "reminders_sent >= 0 AND reminders_sent <= 2", name=op.f("ck_checkouts_reminders_range")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_checkouts_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recovered_order_id"],
            ["orders.id"],
            name=op.f("fk_checkouts_recovered_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_checkouts_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkouts")),
        sa.UniqueConstraint("shop_id", "token", name=op.f("uq_checkouts_shop_id_token")),
    )
    op.create_index(op.f("ix_checkouts_shop_id"), "checkouts", ["shop_id"], unique=False)
    op.create_index("ix_checkouts_shop_status", "checkouts", ["shop_id", "status"], unique=False)
    op.create_table(
        "inventory_snapshots",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_inventory_snapshots_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
            name=op.f("fk_inventory_snapshots_variant_id_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_snapshots")),
    )
    op.create_index(
        op.f("ix_inventory_snapshots_shop_id"), "inventory_snapshots", ["shop_id"], unique=False
    )
    op.create_index(
        "ix_inventory_snapshots_variant_time",
        "inventory_snapshots",
        ["variant_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "llm_calls",
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "agent",
            sa.Enum(
                "orchestrator",
                "fraud_guard",
                "inventory_planner",
                "cart_recovery",
                "support",
                "review_reputation",
                "revenue_analyst",
                "pricing_advisor",
                name="agent_name",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ok",
                "error",
                "timeout",
                name="llm_call_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "agent IN ('orchestrator', 'fraud_guard', 'inventory_planner', 'cart_recovery', 'support', 'review_reputation', 'revenue_analyst', 'pricing_advisor')",
            name=op.f("ck_llm_calls_agent_name"),
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'error', 'timeout')", name=op.f("ck_llm_calls_llm_call_status")
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_llm_calls_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_llm_calls_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_index(
        "ix_llm_calls_shop_created", "llm_calls", ["shop_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_llm_calls_shop_id"), "llm_calls", ["shop_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=True),
        sa.Column("shopify_line_item_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("sku", sa.String(length=128), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price_minor", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_order_items_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
            name=op.f("fk_order_items_variant_id_variants"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_items_shop_id"), "order_items", ["shop_id"], unique=False)
    op.create_index(op.f("ix_order_items_variant_id"), "order_items", ["variant_id"], unique=False)
    op.create_table(
        "tickets",
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "chat",
                "review",
                name="ticket_channel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "pending",
                "escalated",
                "resolved",
                "closed",
                name="ticket_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("customer_email", sa.String(length=320), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("review_id", sa.Uuid(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("assignee_user_id", sa.Uuid(), nullable=True),
        sa.Column("escalation_reason", sa.String(length=255), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "channel IN ('email', 'chat', 'review')", name=op.f("ck_tickets_ticket_channel")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'pending', 'escalated', 'resolved', 'closed')",
            name=op.f("ck_tickets_ticket_status"),
        ),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"],
            ["users.id"],
            name=op.f("fk_tickets_assignee_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_tickets_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_tickets_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("fk_tickets_review_id_reviews"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_tickets_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_index(op.f("ix_tickets_shop_id"), "tickets", ["shop_id"], unique=False)
    op.create_index("ix_tickets_shop_status", "tickets", ["shop_id", "status"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "approved",
                "rejected",
                name="approval_decision",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "edited_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected')", name=op.f("ck_approvals_approval_decision")
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["action_proposals.id"],
            name=op.f("fk_approvals_proposal_id_action_proposals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_approvals_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_approvals_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_proposal_id"), "approvals", ["proposal_id"], unique=False)
    op.create_index(op.f("ix_approvals_shop_id"), "approvals", ["shop_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "inbound",
                "outbound",
                name="message_direction",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "author_type",
            sa.Enum(
                "customer",
                "agent",
                "human",
                name="message_author",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "author_type IN ('customer', 'agent', 'human')", name=op.f("ck_messages_message_author")
        ),
        sa.CheckConstraint(
            "direction IN ('inbound', 'outbound')", name=op.f("ck_messages_message_direction")
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_messages_author_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_messages_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_messages_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(op.f("ix_messages_shop_id"), "messages", ["shop_id"], unique=False)
    op.create_index(op.f("ix_messages_ticket_id"), "messages", ["ticket_id"], unique=False)
    # ### end Alembic commands ###
    op.execute(AUDIT_LOG_GUARD)
    op.execute(
        "CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION audit_log_guard()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_ticket_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_shop_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_approvals_shop_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_proposal_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_tickets_shop_status", table_name="tickets")
    op.drop_index(op.f("ix_tickets_shop_id"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_order_items_variant_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_shop_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_llm_calls_shop_id"), table_name="llm_calls")
    op.drop_index("ix_llm_calls_shop_created", table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index("ix_inventory_snapshots_variant_time", table_name="inventory_snapshots")
    op.drop_index(op.f("ix_inventory_snapshots_shop_id"), table_name="inventory_snapshots")
    op.drop_table("inventory_snapshots")
    op.drop_index("ix_checkouts_shop_status", table_name="checkouts")
    op.drop_index(op.f("ix_checkouts_shop_id"), table_name="checkouts")
    op.drop_table("checkouts")
    op.drop_index("ix_action_proposals_shop_status", table_name="action_proposals")
    op.drop_index(op.f("ix_action_proposals_shop_id"), table_name="action_proposals")
    op.drop_table("action_proposals")
    op.drop_index(op.f("ix_variants_shop_id"), table_name="variants")
    op.drop_index(op.f("ix_variants_product_id"), table_name="variants")
    op.drop_index(op.f("ix_variants_inventory_item_id"), table_name="variants")
    op.drop_table("variants")
    op.drop_index(op.f("ix_reviews_shop_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_orders_shop_processed", table_name="orders")
    op.drop_index(op.f("ix_orders_shop_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_agent_runs_shop_id"), table_name="agent_runs")
    op.drop_index("ix_agent_runs_shop_agent_started", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_webhook_events_topic"), table_name="webhook_events")
    op.drop_index("ix_webhook_events_shop_status", table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_shop_id"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_usage_counters_shop_id"), table_name="usage_counters")
    op.drop_table("usage_counters")
    op.drop_index(op.f("ix_subscriptions_shop_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_shop_settings_shop_id"), table_name="shop_settings")
    op.drop_table("shop_settings")
    op.drop_index(op.f("ix_products_shop_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_notifications_shop_id"), table_name="notifications")
    op.drop_index("ix_notifications_shop_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_shop_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_customers_shop_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index("ix_audit_log_shop_occurred", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_shop_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_agent_configs_shop_id"), table_name="agent_configs")
    op.drop_table("agent_configs")
    op.drop_table("users")
    op.drop_table("shops")
    # ### end Alembic commands ###
