"""order tracking

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 18:54:01.180998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("tracking_number", sa.String(length=128), nullable=True))
    op.add_column("orders", sa.Column("tracking_url", sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "tracking_url")
    op.drop_column("orders", "tracking_number")
    # ### end Alembic commands ###
